// Jahressummendaten für 2026
const yearData = {
    year: 2026,
    totalSollzeit: "1,344:00",
    totalArbeitszeit: "1,330:25",
    totalGleitzeit: "-13:35",
    totalDifferenz: "-13:35",
    months: {
        january: {
            monthName: "Januar",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "110:25",
            gleitzeit: "-1:35",
            differenz: "-1:35",
            tage: [
                {
                    datum: "01.01 Do",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "Feiertag",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "-8:53",
                    feiertag: true,
                    keinArbeitstag: true
                },
                {
                    datum: "02.01 Fr",
                    kommeGest: "11:06",
                    kommeGer: "11:06",
                    kommeBew: "11:06",
                    geheGest: "19:16",
                    geheGer: "19:16",
                    geheBew: "19:16",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "0:00",
                    arbeitszeit: "7:39",
                    gleitzeitTag: "7:39",
                    gleitzeitMonat: "7:39",
                    gleitzeitGesamt: "-1:13",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "03.01 Sa",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "04.01 So",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "05.01 Mo",
                    kommeGest: "10:57",
                    kommeGer: "10:57",
                    kommeBew: "10:57",
                    geheGest: "19:10",
                    geheGer: "19:10",
                    geheBew: "19:10",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "8:00",
                    arbeitszeit: "7:43",
                    gleitzeitTag: "-0:16",
                    gleitzeitMonat: "7:22",
                    gleitzeitGesamt: "-1:30",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "06.01 Di",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "Urlaub",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "8:00",
                    arbeitszeit: "8:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "7:22",
                    gleitzeitGesamt: "-1:30",
                    feiertag: false,
                    keinArbeitstag: true
                },
                {
                    datum: "07.01 Mi",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "8:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "-8:00",
                    gleitzeitMonat: "-0:37",
                    gleitzeitGesamt: "-9:30",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "08.01 Do",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "09.01 Fr",
                    kommeGest: "10:56",
                    kommeGer: "10:56",
                    kommeBew: "10:56",
                    geheGest: "19:11",
                    geheGer: "19:11",
                    geheBew: "19:11",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "0:00",
                    arbeitszeit: "7:44",
                    gleitzeitTag: "7:44",
                    gleitzeitMonat: "7:07",
                    gleitzeitGesamt: "-1:46",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "10.01 Sa",
                    kommeGest: "10:06",
                    kommeGer: "10:06",
                    kommeBew: "10:06",
                    geheGest: "18:18",
                    geheGer: "18:18",
                    geheBew: "18:18",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "0:00",
                    arbeitszeit: "7:41",
                    gleitzeitTag: "7:41",
                    gleitzeitMonat: "14:49",
                    gleitzeitGesamt: "5:55",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "11.01 So",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "12.01 Mo",
                    kommeGest: "10:57",
                    kommeGer: "10:57",
                    kommeBew: "10:57",
                    geheGest: "19:12",
                    geheGer: "19:12",
                    geheBew: "19:12",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "8:00",
                    arbeitszeit: "7:44",
                    gleitzeitTag: "-0:15",
                    gleitzeitMonat: "14:33",
                    gleitzeitGesamt: "5:39",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "13.01 Di",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "Urlaub",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "8:00",
                    arbeitszeit: "8:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "14:33",
                    gleitzeitGesamt: "5:39",
                    feiertag: false,
                    keinArbeitstag: true
                },
                {
                    datum: "14.01 Mi",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "Zeitausgleich; Urlaub",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "8:00",
                    arbeitszeit: "8:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "14:33",
                    gleitzeitGesamt: "5:39",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "15.01 Do",
                    kommeGest: "11:00",
                    kommeGer: "11:00",
                    kommeBew: "11:00",
                    geheGest: "19:22",
                    geheGer: "19:22",
                    geheBew: "19:22",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "0:00",
                    arbeitszeit: "7:52",
                    gleitzeitTag: "7:52",
                    gleitzeitMonat: "22:25",
                    gleitzeitGesamt: "13:32",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "16.01 Fr",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "17.01 Sa",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "18.01 So",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "19.01 Mo",
                    kommeGest: "08:11",
                    kommeGer: "08:11",
                    kommeBew: "08:11",
                    geheGest: "19:06",
                    geheGer: "19:06",
                    geheBew: "19:06",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:45",
                    sollzeit: "8:00",
                    arbeitszeit: "10:09",
                    gleitzeitTag: "2:09",
                    gleitzeitMonat: "24:34",
                    gleitzeitGesamt: "15:41",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "20.01 Di",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "Urlaub",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "8:00",
                    arbeitszeit: "8:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "24:34",
                    gleitzeitGesamt: "15:41",
                    feiertag: false,
                    keinArbeitstag: true
                },
                {
                    datum: "21.01 Mi",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "8:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "-8:00",
                    gleitzeitMonat: "16:34",
                    gleitzeitGesamt: "7:41",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "22.01 Do",
                    kommeGest: "10:51",
                    kommeGer: "10:51",
                    kommeBew: "10:51",
                    geheGest: "19:21",
                    geheGer: "19:21",
                    geheBew: "19:21",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "0:00",
                    arbeitszeit: "7:58",
                    gleitzeitTag: "7:58",
                    gleitzeitMonat: "24:33",
                    gleitzeitGesamt: "15:40",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "23.01 Fr",
                    kommeGest: "10:54",
                    kommeGer: "10:54",
                    kommeBew: "10:54",
                    geheGest: "19:40",
                    geheGer: "19:40",
                    geheBew: "19:40",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "0:00",
                    arbeitszeit: "8:15",
                    gleitzeitTag: "8:15",
                    gleitzeitMonat: "32:49",
                    gleitzeitGesamt: "23:56",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "24.01 Sa",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "25.01 So",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "26.01 Mo",
                    kommeGest: "10:46",
                    kommeGer: "10:46",
                    kommeBew: "10:46",
                    geheGest: "19:16",
                    geheGer: "19:16",
                    geheBew: "19:16",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "8:00",
                    arbeitszeit: "7:59",
                    gleitzeitTag: "-0:00",
                    gleitzeitMonat: "32:49",
                    gleitzeitGesamt: "23:55",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "27.01 Di",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "8:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "-8:00",
                    gleitzeitMonat: "24:49",
                    gleitzeitGesamt: "15:55",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "28.01 Mi",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "8:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "-8:00",
                    gleitzeitMonat: "16:49",
                    gleitzeitGesamt: "7:55",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "29.01 Do",
                    kommeGest: "",
                    kommeGer: "",
                    kommeBew: "",
                    geheGest: "",
                    geheGer: "",
                    geheBew: "",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "",
                    sollzeit: "0:00",
                    arbeitszeit: "0:00",
                    gleitzeitTag: "0:00",
                    gleitzeitMonat: "0:00",
                    gleitzeitGesamt: "0:00",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "30.01 Fr",
                    kommeGest: "10:54",
                    kommeGer: "10:54",
                    kommeBew: "10:54",
                    geheGest: "19:31",
                    geheGer: "19:31",
                    geheBew: "19:31",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:30",
                    sollzeit: "0:00",
                    arbeitszeit: "8:07",
                    gleitzeitTag: "8:07",
                    gleitzeitMonat: "24:56",
                    gleitzeitGesamt: "16:03",
                    feiertag: false,
                    keinArbeitstag: false
                },
                {
                    datum: "31.01 Sa",
                    kommeGest: "14:43",
                    kommeGer: "14:43",
                    kommeBew: "14:43",
                    geheGest: "18:19",
                    geheGer: "18:19",
                    geheBew: "18:19",
                    abwesenheit: "",
                    azProfil: "24 Stunden Woche (mo,di,mi)",
                    pause: "0:00",
                    sollzeit: "0:00",
                    arbeitszeit: "3:36",
                    gleitzeitTag: "3:36",
                    gleitzeitMonat: "28:33",
                    gleitzeitGesamt: "19:39",
                    feiertag: false,
                    keinArbeitstag: false
                }
            ]
        },
        february: {
            monthName: "Februar",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        march: {
            monthName: "März",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        april: {
            monthName: "April",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        may: {
            monthName: "Mai",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        june: {
            monthName: "Juni",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        july: {
            monthName: "Juli",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        august: {
            monthName: "August",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        september: {
            monthName: "September",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        october: {
            monthName: "Oktober",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        november: {
            monthName: "November",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        },
        december: {
            monthName: "Dezember",
            year: 2026,
            sollzeit: "112:00",
            arbeitszeit: "112:00",
            gleitzeit: "0:00",
            differenz: "0:00",
            tage: []
        }
    }
};
